apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: students-grades-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/neokol/msc-students-portal/backend:latest
        env:
        - name: DATABASE_URL
          value: "postgresql://neokol:81829192@postgres:5432/AcademicPortal"
        - name: ACCESS_TOKEN_EXPIRE_MINUTES
          value: "300"
        - name: ALGORITHM
          value: "HS256"
        - name: SECRET_KEY
          value: "your_secret_key"
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: github-packages