apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: students-grades-portal
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30000
  selector:
    app: backend
