apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: students-grades-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: docker.pkg.github.com/neokol/msc-students-portal/backend:latest
        env:
        - name: DATABASE_URL
          value: "postgresql://neokol:81829192@postgres:5432/AcademicPortal"
        ports:
        - containerPort: 8000
