apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: students-grades-portal
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 30001  # Choose an available port in the range 30000-32767
  selector:
    app: frontend