apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: students-grades-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/neokol/msc-students-portal/frontend:latest
        ports:
        - containerPort: 3000
