apiVersion: v1
kind: Service
metadata:
  name: mailhog
  namespace: students-grades-portal
spec:
  type: LoadBalancer
  ports:
  - port: 1025
    targetPort: 1025
  - port: 8025
    targetPort: 8025
  selector:
    app: mailhog
