apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: students-grades-portal
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: pgadmin
