apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: students-grades-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_USER
          value: "neokol"
        - name: POSTGRES_PASSWORD
          value: "81829192"
        - name: POSTGRES_DB
          value: "AcademicPortal"
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        emptyDir: {}
